//获取页面初始数据
export const FETCH_PRE_DATA_REQUEST = 'PAGES/DEMO1/FETCH_PRE_DATA_REQUEST';
export const FETCH_PRE_DATA_SUCCESS = 'PAGES/DEMO1/FETCH_PRE_DATA_SUCCESS';
export const FETCH_PRE_DATA_FAILURE = 'PAGES/DEMO1/FETCH_PRE_DATA_FAILURE';




